import type { Metadata } from "next";
import "./reset.css";
import "./general.css"


export const metadata: Metadata = {
  title: "Portfolio Steven",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body>
        {children}
      </body>
    </html>
  );
}
